---
phpmyadmin_user: "admin"
phpmyadmin_password: "admin"
mysql_root_password: "summerbod123"
app_user: "admin"
http_host: "summerbod"
http_conf: "summerbod.conf"
http_port: "80"
disable_default: true