---
phpmyadmin_user: "yourusername"
phpmyadmin_password: "yourpassword"
mysql_root_password: "yourpassword"
app_user: "yourusername"
http_host: "summerbod"
http_conf: "summerbod.conf"
http_port: "80"
disable_default: true
