#!/bin/bash

############################
## phpmyadmin instalation ##
############################

cd
wget https://files.phpmyadmin.net/phpMyAdmin/5.1.3/phpMyAdmin-5.1.3-english.tar.gz
tar xvf phpMyAdmin-5.1.3-english.tar.gz
sudo mv phpMyAdmin-5.1.3-english/ /usr/share/phpmyadmin

#############################
## Directory configuration ##
#############################

cd
sudo mkdir -p /var/lib/phpmyadmin/tmp
sudo chown -R www-data:www-data /var/lib/phpmyadmin
sudo cp /usr/share/phpmyadmin/config.sample.inc.php /usr/share/phpmyadmin/config.inc.php
cat wiket/Ansible/files/config.inc.php | sudo tee /usr/share/phpmyadmin/config.inc.php > /dev/null

##############################
## Configuration with MySQL ##
##############################

sudo mariadb < /usr/share/phpmyadmin/sql/create_tables.sql -u root -p
sudo mariadb -u root -p -e "GRANT SELECT, INSERT, UPDATE, DELETE ON phpmyadmin.* TO 'pma'@'localhost' IDENTIFIED BY 'root';GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' IDENTIFIED BY '$pblsummerbod' WITH GRANT OPTION;exit"

########################
## File configuration ##
########################

cd
sudo cp wiket/Ansible/files/phpmyadmin.conf /etc/apache2/conf-available/phpmyadmin.conf
sudo a2enconf phpmyadmin.conf
sudo systemctl reload apache2

##########################
## Access configuration ##
##########################

cd
sudo cp wiket/Ansible/files/.htaccess /usr/share/phpmyadmin/.htaccess
sudo htpasswd -c /usr/share/phpmyadmin/.htpasswd admin

sudo systemctl reload apache2