#!/bin/sh

#####################
## Starting plugin ##
#####################

sudo mkdir -p /etc/ansible
echo '[sudo_become_plugin]' | sudo tee -a /etc/ansible/ansible.conf > /dev/null
echo 'flags = -H -S' | sudo tee -a /etc/ansible/ansible.conf > /dev/null

######################
## Launch Create VM ##
######################

cd
./Ansible/shell/Create_VM